spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/realestate
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true



logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.type: trace

service:
  open-api:
    service-key: LmRJUQ0Km%2BT4429%2B9gaX%2BJaoKq4fsCkqP4YQ%2BZu4l9wfdbw5Cdv9ZkBkzIKgJucOr3bYbaxeMyOUkXnkMTAEXQ%3D%3D
    apt-url: http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade
    house-url: http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcSHTrade
    mention-url: http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcRHTrade

